# Tools for Collaboration {#sec-tools}

A big team science group usually produces scientific products, like registration plans, data sets, analysis code, and manuscripts. you'll need a way to track and organise all of this. Here are a few of my favourite tools that you can set up accounts for your teams.

It's probably a good idea to set up a dedicated email address for the group, so you can use it as the login email for all of your other accounts and they can be easily transferred when the leadership team changes.

## Google

Google docs, sheets, and forms are a useful way to collaborate on documents with a large group. Most people will have no problems with access.

If someone in your core group works at a university where they can make a Google [Shared Drive](https://support.google.com/a/users/answer/9310249), this can be a nice way to organise documents. Members can be added to the shared drive and can create documents where all members have default permission to edit.

If you can't make a shared drive, you can set up a new Google account for your team and keep all documents in a folder on that account's [Google Drive](https://drive.google.com/drive/). Documents made by team members will need to give editor permissions to the group account. 


## Calendar

As your group grows, you'll need to keep track of meetings and deadlines. A group calendar can help with this. [Google Calendar](https://calendar.google.com/) is probably the easiest to set up, especially if you already made a Google account for the team.

## OSF

The [Open Science Framework](https://osf.io) is a great place to archive your documents and other materials once you are finished collaborating on them. The projects have a modular structure, so you can give editing rights to different team members for specific projects or aspects of projects.

Make a project for your team. (Set the storage location to Germany if your team has European members so they can store research data there without [GDPR](https://gdpr.eu/what-is-gdpr/) problems.) Create a new component for each project and add the appropriate contributors.

## Zotero

[Zotero](https://www.zotero.org/) is probably the best and most open reference manager there is. You can set up a [shared library for your group](https://www.zotero.org/groups/) that members can join. You can use this as a way to track your group's outputs, or as a shared reference manager for projects. You can set the library to be totally private or publicly viewable.

## Github {#sec-github}

If your group will have any open code, including analysis scripts, you should think about setting up a free [GitHub organisation](https://github.com/organizations/plan). [Code Check Club](https://github.com/code-check-club) is a good example of a group GitHub page.

## Zenodo

[Zenodo](https://zenodo.org/) is a research repository that is great for giving DOIs to coding projects (it has GitHub integration). We use Zenodo for the [PsyTeachR](https://psyteachr.github.io) book series. You can make a [Community](https://zenodo.org/communities/) on Zenodo to curate your organisation's outputs.
