# Visión general {-}

Esta guía es una de las "charlas" de la serie de talleres de [ABRIR](https://abrirpsy.org): [Mayor representacion: Una Visión para la Ciencia Inclusiva de Grandes Equipos](https://abrirpsy.org/program-updated-increased-representation-workshop-series/). La autora, Lisa DeBruine, estará disponible para responder preguntas de forma asíncrona en el taller de Slack durante la conferencia, del 22 al 24 de septiembre de 2022.

Esta guía está dirigida a personas que deseen iniciar equipos de ciencia colaborativa (Big-Team) desde las bases, con poco o ningún apoyo financiero o administrativo. Se cubirán los aspectos organizativos de cómo reclutar miembros, configurar la gobernanza, comunicarse con el equipo, configurar y utilizar cuentas de redes sociales, utilizar herramientas de colaboración y crear un sitio web.

Recuerde que esta es solo una perspectiva. Mis cualificaciones para dar consejos son ser miembro fundadora y actual Directora Asociada del [Psychological Science Accelerator](https://psysciacc.org), fundadora de [ManyFaces](https://twitter.com/ManyFacesTeam), organizadora del [Code Check Club](https://github.com/code-check-club), y habiendo sido anteriormente responsable de las páginas web y comunicaciones de Human Behavior and Evolution Society y de European Human Behavior and Evolution Association. He tenido el enorme privilegio de ser hablante de inglés como primer idioma en una universidad intensiva en investigación, bien financiada y solidaria en Escocia. Espero que esta guía pueda ser el comienzo para una guía más extensa con más voces y perspectivas.


