# Genel Bakış {-}

Bu kılavuz, [ABRIR](https://abrirpsy.org)'in atölye serisi için yapılan "konuşmalardan" biridir: [Artan Temsil: Kapsayıcı Büyük Ekip Bilimine Vizyoner Bir Bakış](https://abrirpsy.org/program-updated-increased-representation-workshop-series/). Yazar, Lisa DeBruine, 22-24 Eylül 2022 tarihleri arasında konferans kapsamındaki asenkron atölyeler esnasında senkron olarak soruları cevaplamak için Slack uygulamasında ulaşılabilir durumda olacaktır.

Bu kılavuz, çok az veya hiç finansal ya da kurumsal desteği olmayan ve büyük ekip bilimi grupları oluşturmak isteyen kişileri hedeflemektedir. Kılavuz, üyelerin nasıl dahil edileceğinin, nasıl denetim kurulacağının, takımla nasıl iletişim kurulacağının, sosyal medya hesaplarının nasıl oluşturulacağının ve kullanılacağının, iş birliği için araçların nasıl kullanılacağının ve bir web sayfasının nasıl oluşturulacağının organizasyonel taraflarını ele alacaktır.

Unutmayınız ki bu sadece tek bir bakış açısıdır. Yavsiye vermek için dayanabileceğim yeterliklerim [Psychological Science Accelerator](https://psysciacc.org)'ın kurucu üyesi ve mevcut yönetici yardımcısı olmak, [ManyFaces](https://twitter.com/ManyFacesTeam)'in kurucusu olmak, [Code Check Club](https://github.com/code-check-club)'ın düzenleyicisi olmak ve İnsan Davranışı ve Evrim Topluluğu ile Avrupa İnsan Davranışı ve Evrim Derneği'nin web ve iletişimden sorumlu yetkisi deneyimlerine sahip olmaktır. İskoçya'da destekleyici, iyi finanse edilen, araştırma-yoğunluklu bir üniversitede ana dili İngilizce olan biri olmanın muazzam ayrıcalıklarına sahip oldum. Umarım bu kılavuz daha fazla sese ve bakış açısına sahip daha kapsamlı bir kılavuzun başlangıcı olabilir.


